M48
; DRILL file {KiCad 9.0.3} date 2026-02-15T20:10:58-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-02-15T20:10:58-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.4882Y-0.8071
X4.4882Y-3.1299
X8.0709Y-0.8071
X8.0709Y-3.1299
M30
